#!/bin/bash

cd "$(dirname "$0")"
cd ..

mkdir public

echo installing in main
npm install

cd admin
echo installing in admin
npm install
cd ..

cd server
echo installing in server
npm install
cd ..

echo building in main
export NODE_ENV=production
npm run build

cd admin
echo building in admin
npm run-script ng build admin -c production
cd ..

cd assets
node getassets.js
cd ..

