#!/bin/bash

cd "$(dirname "$0")"
cd ..

mkdir public
npm install

export NODE_ENV=production
npm run build

cd assets
node getassets.js
cd ..

cd admin
npm install
npm run-script ng build admin -c production

cd ..

