#!/bin/bash

cd "$(dirname "$0")"
cd ../..

bash scripts/build-prod

mkdir -p distrib/ScratchPortable
rm -f distrib/ScratchPortable/*.*

cd server
node scratch_portable.js
cp node_modules/sqlite3/lib/binding/*/node_sqlite3.node ../distrib/ScratchPortable/
cd ..

